import type { Metadata } from "next";

/** Live site origin. Set NEXT_PUBLIC_SITE_URL once the custom domain is live. */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://virtualcaptains.vercel.app").replace(
  /\/$/,
  "",
);

export const SITE_NAME = "Virtual Captains";

/** Generated by app/opengraph-image.tsx — the default share card. */
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Virtual Captains — Sales Training, SalesX & Sales Floor Management",
};

type PageSeo = {
  /** Page title without the brand; the root layout appends " | Virtual Captains". */
  title: string;
  description: string;
  /** Route path, e.g. "/about". Becomes the canonical URL. */
  path: string;
  /** Use the title as-is (no brand suffix), e.g. for the home page. */
  absoluteTitle?: boolean;
  keywords?: string[];
  /** Keep the page out of search results (thin or utility pages). */
  noIndex?: boolean;
};

/**
 * Full SEO metadata for a page: title, description, canonical URL, Open
 * Graph + Twitter share cards and robots. Use in every page's `metadata`.
 */
export function pageMetadata({ title, description, path, absoluteTitle, keywords, noIndex }: PageSeo): Metadata {
  const fullTitle = absoluteTitle ? title : `${title} | ${SITE_NAME}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    keywords,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_IN",
      url: path,
      title: fullTitle,
      description,
      images: [DEFAULT_OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [DEFAULT_OG_IMAGE.url],
    },
    robots: noIndex ? { index: false, follow: true } : undefined,
  };
}
