"use client";

import { useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import { LAND_DOTS } from "./globeDots";

gsap.registerPlugin(ScrollTrigger);

type Location = {
  name: string;
  country: string;
  lon: number;
  lat: number;
};

const LOCATIONS: Location[] = [
  { name: "Dubai", country: "United Arab Emirates", lon: 55.27, lat: 25.2 },
  {
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    lon: 54.37,
    lat: 24.45,
  },
  { name: "Riyadh", country: "Saudi Arabia", lon: 46.72, lat: 24.71 },
  { name: "Doha", country: "Qatar", lon: 51.53, lat: 25.29 },
  { name: "Manama", country: "Bahrain", lon: 50.59, lat: 26.23 },
  { name: "Kuwait City", country: "Kuwait", lon: 47.98, lat: 29.38 },
  { name: "Muscat", country: "Oman", lon: 58.41, lat: 23.59 },
];

/**
 * Camera waypoints the scroll position moves the globe through: an
 * establishing world view, a swing into the Gulf, each client city in turn,
 * then a pull-back that leaves every marker on screen at once.
 */
const JOURNEY: { lon: number; lat: number; zoom: number; label?: string }[] = [
  { lon: 14, lat: 16, zoom: 1 },
  { lon: 44, lat: 24, zoom: 1.35, label: "The Gulf" },
  { lon: 55.27, lat: 25.2, zoom: 2.2, label: "Dubai" },
  { lon: 46.72, lat: 24.71, zoom: 2.2, label: "Riyadh" },
  { lon: 51.53, lat: 25.29, zoom: 2.2, label: "Doha" },
  { lon: 58.41, lat: 23.59, zoom: 2.2, label: "Muscat" },
  { lon: 52, lat: 25, zoom: 1.45, label: "Middle East" },
];

const DEG = Math.PI / 180;
const ACCENT = "52, 120, 229"; // #3478e5
const HIGHLIGHT = "#e7ff3d";

/** Shortest signed angular distance from a to b, in degrees. */
function angleDelta(a: number, b: number) {
  return ((((b - a) % 360) + 540) % 360) - 180;
}

function smoothstep(t: number) {
  return t * t * (3 - 2 * t);
}

/**
 * "Empowering sales professionals worldwide" — a canvas globe built from
 * precomputed land dots (see globeDots.ts, generated by
 * scripts/generate-globe-dots.mjs, so nothing geo-related ships at runtime).
 *
 * Scroll drives a camera along JOURNEY: the globe rotates and zooms from a
 * world view into each Gulf city in turn. Desktop pins the section for the
 * duration; smaller screens scrub the same path as the section passes by,
 * without hijacking the scroll.
 */
export default function CrossCountry() {
  const sectionRef = useRef<HTMLElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);
  const paragraphRef = useRef<HTMLParagraphElement>(null);
  const globeWrapRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const progressRef = useRef(0);

  useGSAP(
    () => {
      const canvas = canvasRef.current;
      const wrap = globeWrapRef.current;
      if (!canvas || !wrap) return;

      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      const prefersReducedMotion = window.matchMedia(
        "(prefers-reduced-motion: reduce)",
      ).matches;

      const fontSans =
        getComputedStyle(document.documentElement)
          .getPropertyValue("--font-sans")
          .trim() || "system-ui, sans-serif";

      let width = 0;
      let height = 0;

      const resize = () => {
        const dpr = Math.min(window.devicePixelRatio || 1, 2);
        const rect = wrap.getBoundingClientRect();
        width = rect.width;
        height = rect.height;
        canvas.width = Math.round(width * dpr);
        canvas.height = Math.round(height * dpr);
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      };

      resize();
      const resizeObserver = new ResizeObserver(resize);
      resizeObserver.observe(wrap);

      const draw = (time: number) => {
        if (!width || !height) return;

        const cx = width / 2;
        const cy = height / 2;
        const baseRadius = Math.min(width, height) * 0.38;

        // --- camera: interpolate along the journey ---------------------
        const t = progressRef.current * (JOURNEY.length - 1);
        const i = Math.min(Math.floor(t), JOURNEY.length - 2);
        const local = smoothstep(t - i);
        const from = JOURNEY[i];
        const to = JOURNEY[i + 1];

        const centerLon = from.lon + angleDelta(from.lon, to.lon) * local;
        const centerLat = from.lat + (to.lat - from.lat) * local;
        const zoom = from.zoom + (to.zoom - from.zoom) * local;
        const radius = baseRadius * zoom;

        const l0 = centerLon * DEG;
        const p0 = centerLat * DEG;
        const sinP0 = Math.sin(p0);
        const cosP0 = Math.cos(p0);

        /** Orthographic projection; null when the point is on the far side. */
        const project = (lon: number, lat: number) => {
          const l = lon * DEG - l0;
          const p = lat * DEG;
          const cosP = Math.cos(p);
          const cosC = sinP0 * Math.sin(p) + cosP0 * cosP * Math.cos(l);
          if (cosC <= 0.02) return null;
          return {
            x: cx + radius * cosP * Math.sin(l),
            y: cy - radius * (cosP0 * Math.sin(p) - sinP0 * cosP * Math.cos(l)),
            depth: cosC,
          };
        };

        ctx.clearRect(0, 0, width, height);

        // Everything is drawn through a fixed circular porthole at
        // baseRadius: zooming flies the camera closer without the globe
        // outgrowing its own outline into a hard-edged square.
        ctx.save();
        ctx.beginPath();
        ctx.arc(cx, cy, baseRadius, 0, Math.PI * 2);
        ctx.clip();

        // --- sphere body ------------------------------------------------
        const sphere = ctx.createRadialGradient(
          cx - baseRadius * 0.35,
          cy - baseRadius * 0.4,
          baseRadius * 0.1,
          cx,
          cy,
          baseRadius,
        );
        sphere.addColorStop(0, "rgba(255, 255, 255, 0.18)");
        sphere.addColorStop(0.65, "rgba(255, 255, 255, 0.08)");
        sphere.addColorStop(1, "rgba(255, 255, 255, 0.02)");
        ctx.beginPath();
        ctx.arc(cx, cy, baseRadius, 0, Math.PI * 2);
        ctx.fillStyle = sphere;
        ctx.fill();

        // --- land ---------------------------------------------------------
        const dotRadius = Math.max(0.75, baseRadius * 0.008 * Math.sqrt(zoom));
        for (const [lon, lat] of LAND_DOTS) {
          const point = project(lon, lat);
          if (!point) continue;
          // fade towards the limb so the sphere reads as a sphere
          ctx.globalAlpha = 0.25 + 0.75 * point.depth;
          ctx.beginPath();
          ctx.arc(point.x, point.y, dotRadius, 0, Math.PI * 2);
          ctx.fillStyle = "#ffffff";
          ctx.fill();
        }
        ctx.globalAlpha = 1;

        // --- client markers -------------------------------------------------
        const activeLabel = (() => {
          let best: { label: string; weight: number } | null = null;
          JOURNEY.forEach((wp, index) => {
            if (!wp.label) return;
            // flat top around each waypoint so a city's label holds at full
            // strength while you dwell on it, instead of peaking for an instant
            const distance = Math.abs(t - index);
            const weight =
              distance <= 0.3 ? 1 : Math.max(0, 1 - (distance - 0.3) / 0.45);
            if (weight > 0 && (!best || weight > best.weight)) {
              best = { label: wp.label, weight };
            }
          });
          return best as { label: string; weight: number } | null;
        })();

        const pulse = 0.5 + 0.5 * Math.sin(time * 0.0022);

        for (const location of LOCATIONS) {
          const point = project(location.lon, location.lat);
          if (!point) continue;

          const isFocused =
            activeLabel?.label === location.name && activeLabel.weight > 0.35;
          const alpha = Math.min(1, point.depth * 1.6);

          // halo
          ctx.globalAlpha = alpha * (isFocused ? 0.28 + 0.22 * pulse : 0.2);
          ctx.beginPath();
          ctx.arc(
            point.x,
            point.y,
            (isFocused ? 11 + 5 * pulse : 6) * Math.min(zoom, 1.6),
            0,
            Math.PI * 2,
          );
          ctx.fillStyle = isFocused ? HIGHLIGHT : "rgba(255, 255, 255, 0.6)";
          ctx.fill();

          // core
          ctx.globalAlpha = alpha;
          ctx.beginPath();
          ctx.arc(point.x, point.y, isFocused ? 4 : 2.6, 0, Math.PI * 2);
          ctx.fillStyle = isFocused ? HIGHLIGHT : "#ffffff";
          ctx.fill();

          if (isFocused) {
            ctx.strokeStyle = "rgba(16,16,16,0.55)";
            ctx.lineWidth = 0.8;
            ctx.stroke();
          }

          // label on the focused city
          if (isFocused) {
            const labelAlpha = (activeLabel.weight - 0.35) / 0.65;
            ctx.globalAlpha = Math.min(1, labelAlpha) * alpha;

            const leader = width < 480 ? 20 : 26;
            const labelY = point.y - leader;
            const isRightSide = point.x > cx;
            const textX = isRightSide ? point.x - leader - 16 : point.x + leader + 16;

            ctx.beginPath();
            if (isRightSide) {
              ctx.moveTo(point.x - 6, point.y - 6);
              ctx.lineTo(point.x - leader, labelY);
              ctx.lineTo(point.x - leader - 10, labelY);
            } else {
              ctx.moveTo(point.x + 6, point.y - 6);
              ctx.lineTo(point.x + leader, labelY);
              ctx.lineTo(point.x + leader + 10, labelY);
            }
            ctx.strokeStyle = "rgba(255, 255, 255, 0.6)";
            ctx.lineWidth = 1;
            ctx.stroke();

            // white plate so the label stays readable over the land dots
            ctx.font = `600 13px ${fontSans}`;
            const nameWidth = ctx.measureText(location.name).width;
            ctx.font = `400 11px ${fontSans}`;
            const countryWidth = ctx.measureText(location.country).width;
            const plateWidth = Math.max(nameWidth, countryWidth) + 14;

            const plateX = isRightSide ? textX - plateWidth + 7 : textX - 7;
            const contentX = isRightSide ? textX - plateWidth + 14 : textX;

            ctx.fillStyle = "rgba(255,255,255,0.96)";
            ctx.beginPath();
            ctx.roundRect(plateX, labelY - 17, plateWidth, 34, 4);
            ctx.fill();

            ctx.textAlign = "left";
            ctx.font = `600 13px ${fontSans}`;
            ctx.textBaseline = "bottom";
            ctx.fillStyle = "#101010";
            ctx.fillText(location.name, contentX, labelY - 1);

            ctx.font = `400 11px ${fontSans}`;
            ctx.textBaseline = "top";
            ctx.fillStyle = "rgba(16,16,16,0.6)";
            ctx.fillText(location.country, contentX, labelY + 3);
          }
        }
        ctx.globalAlpha = 1;

        ctx.restore();

        // --- sphere outline (drawn over the clip, so it stays crisp) --------
        ctx.beginPath();
        ctx.arc(cx, cy, baseRadius, 0, Math.PI * 2);
        ctx.strokeStyle = "rgba(255, 255, 255, 0.28)";
        ctx.lineWidth = 1;
        ctx.stroke();

        // --- region caption (shown for the non-city waypoints) --------------
        if (
          activeLabel &&
          !LOCATIONS.some((l) => l.name === activeLabel.label)
        ) {
          ctx.globalAlpha = activeLabel.weight;
          ctx.font = `500 11px ${fontSans}`;
          ctx.textAlign = "center";
          ctx.textBaseline = "middle";
          ctx.fillStyle = "rgba(255, 255, 255, 0.85)";
          ctx.letterSpacing = "0.18em";
          ctx.fillText(activeLabel.label.toUpperCase(), cx, height - 10);
          ctx.letterSpacing = "0px";
          ctx.globalAlpha = 1;
        }
      };

      // A ticker only while the section is on screen — no point burning frames
      // for a globe nobody can see. This has to be an IntersectionObserver
      // rather than a ScrollTrigger: the section gets pinned (position:fixed),
      // which stops a trigger on that same element from tracking it, and the
      // render loop would freeze mid-flight.
      let running = false;
      const tick = (time: number) => draw(time);
      const startLoop = () => {
        if (running) return;
        running = true;
        gsap.ticker.add(tick);
      };
      const stopLoop = () => {
        if (!running) return;
        running = false;
        gsap.ticker.remove(tick);
      };

      const visibility = new IntersectionObserver(
        ([entry]) => (entry.isIntersecting ? startLoop() : stopLoop()),
        { rootMargin: "200px" },
      );
      visibility.observe(sectionRef.current!);

      const mm = gsap.matchMedia();

      if (prefersReducedMotion) {
        // Land on the final pull-back framing and stay there.
        progressRef.current = 1;
        draw(0);
      } else {
        gsap.set([headingRef.current, paragraphRef.current], {
          opacity: 0,
          y: 20,
        });
        gsap.set(globeWrapRef.current, { opacity: 0, scale: 0.94 });

        const intro = gsap.timeline({
          scrollTrigger: {
            trigger: sectionRef.current,
            start: "top 70%",
            once: true,
          },
        });
        intro
          .to(headingRef.current, {
            opacity: 1,
            y: 0,
            duration: 0.7,
            ease: "power2.out",
          })
          .to(
            globeWrapRef.current,
            { opacity: 1, scale: 1, duration: 1, ease: "power2.out" },
            "-=0.4",
          )
          .to(
            paragraphRef.current,
            { opacity: 1, y: 0, duration: 0.6, ease: "power2.out" },
            "-=0.6",
          );

        const camera = { value: 0 };
        const applyProgress = () => {
          progressRef.current = camera.value;
        };

        // Desktop pins and flies the camera; below that the same path scrubs as
        // the section travels through the viewport, so mobile keeps its scroll.
        mm.add("(min-width: 1024px)", () => {
          const trigger = ScrollTrigger.create({
            trigger: sectionRef.current,
            start: "top top",
            end: "+=320%",
            pin: true,
            scrub: 0.6,
            onUpdate: (self) => {
              progressRef.current = self.progress;
            },
          });
          const spacer = (trigger as unknown as { spacer?: HTMLElement }).spacer;
          if (spacer) {
            spacer.style.backgroundColor = "#ffffff";
          }
          return () => trigger.kill();
        });

        mm.add("(max-width: 1023px)", () => {
          const trigger = ScrollTrigger.create({
            trigger: sectionRef.current,
            start: "top 85%",
            end: "bottom 15%",
            scrub: 0.6,
            onUpdate: (self) => {
              progressRef.current = self.progress;
            },
          });
          return () => trigger.kill();
        });

        applyProgress();
      }

      return () => {
        stopLoop();
        visibility.disconnect();
        resizeObserver.disconnect();
        mm.revert();
      };
    },
    { scope: sectionRef },
  );

  return (
    <section
      ref={sectionRef}
      data-nav-section="Cross Country"
      data-nav-theme="light"
      className="relative -mt-0.5 z-10 flex min-h-screen w-full flex-col items-center justify-center overflow-hidden px-6 py-[clamp(28px,5vh,72px)] text-[#101010] sm:px-10 lg:px-16"
      style={{
        background:
          "linear-gradient(180deg, #ffffff 0%, #9fc3fa 20%, #205ee0 48%, #0d286e 75%, #050608 100%)",
      }}
    >
      <div
        className="pointer-events-none absolute inset-0 z-0 opacity-40"
        style={{
          backgroundImage:
            "radial-gradient(rgba(0,0,0,0.1) 0.65px, transparent 0.65px)",
          backgroundSize: "9px 9px",
        }}
      />

      <div className="relative z-10 flex w-full max-w-[1920px] flex-col items-center">
        <h2
          ref={headingRef}
          className="max-w-3xl text-center font-serif text-[clamp(1.5rem,1.6vw+1.2vh,2.5rem)] font-normal leading-[1.2] text-[#101010]"
        >
          <span className="block">Empowering sales</span>
          <span className="block">
            professionals{" "}
            <span className="italic text-[#2563eb]">worldwide</span>
          </span>
        </h2>

        <div
          ref={globeWrapRef}
          className="mt-[clamp(12px,2.5vh,36px)] aspect-square w-[min(620px,56vh,88vw)]"
        >
          <canvas ref={canvasRef} className="h-full w-full " />
        </div>

        <p
          ref={paragraphRef}
          className="mx-auto mt-[clamp(12px,2.5vh,32px)] max-w-150 text-center font-sans text-[13px] leading-relaxed text-white/85 sm:text-[14px]"
        >
          From high-growth markets to global enterprises, we help individuals
          and organisations build sales capabilities that drive real business
          impact.
        </p>
      </div>
    </section>
  );
}
